// creating an array and passing the number, questions, options, and answers
let questions = [
    {
    numb: 1,
    question: "ประเทศไทยมีกี่จังหวัด",
    answer: "77",
    options: [
      "70",
      "20",
      "77",
      "55"
    ]
  },
    {
    numb: 2,
    question: "อาจาร์ที่หล่อที่สุดในมหาลัยมีชื่อว่าอะไร",
    answer: "อัศวนนทปกรณ์ ธเนศวีรภัทร",
    options: [
      "อัศวนนทปกรณ์ ธเนศวีรภัทร",
      "สันตื",
      "จันทร์โอชา",
      "ผมนี้และหล่อสุด"
    ]
  },
    {
    numb: 3,
    question: "เอกอะไรมีผ.ช.หล่อมากที่สุด",
    answer: "ฟิสิกส์",
    options: [
      "ฟิสิกส์",
      "ชีวะ",
      "เคมี",
      "ภาษาไทย"
    ]
  },
    {
    numb: 4,
    question: "อาจาร์ในมหาลัยใครใจดีที่สุด",
    answer: "อัศวนนทปกรณ์ ธเนศวีรภัทร",
    options: [
      "อัศวนนทปกรณ์ ธเนศวีรภัทร",
      "อาจาร์ไก่",
      "ขจร",
      "หนูพิม"
    ]
  },
    {
    numb: 5,
    question: "เมนูอะไรอาจาร์ อัศวนนทปกรณ์ ธเนศวีรภัทร กินไม่ได้",
    answer: "ข้าว",
    options: [
      "ข้าว",
      "วุ้นเส้น",
      "วุ้นเส้น",
      "วุ้นเส้น"
    ]
  },
  // you can uncomment the below codes and make duplicate as more as you want to add question
  // but remember you need to give the numb value serialize like 1,2,3,5,6,7,8,9.....

  //   {
  //   numb: 6,
  //   question: "Your Question is Here",
  //   answer: "Correct answer of the question is here",
  //   options: [
  //     "Option 1",
  //     "option 2",
  //     "option 3",
  //     "option 4"
  //   ]
  // },
];
